name: 'Dynamic Code Owners Reviewer Bot'
description: 'Enforces multi-owner mandatory approvals on Pull Requests based on CODEOWNERS file'
author: 'Robbie dela Victoria'

branding:
  icon: 'users'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}

outputs:
  result:
    description: 'Result of the code owners check (success/failure)'
  required_owners:
    description: 'JSON array of required owner groups'
  missing_approvals:
    description: 'JSON array of owner groups that still need approval'

runs:
  using: 'node20'
  main: 'dist/index.js'
