name: 'Code Owners Approval Bot'

on:
  pull_request:
    types:
      - opened           # When PR is first created
      - synchronize      # When new commits are pushed
      - ready_for_review # When PR is marked ready for review
  pull_request_review:
    types:
      - submitted        # When a review is submitted
      - dismissed        # When a review is dismissed

permissions:
  contents: read         # Read repository content and CODEOWNERS
  pull-requests: write   # Create and update PR comments
  checks: write         # Create and update status checks
  issues: write         # Create PR comments (PRs are issues in GitHub API)

jobs:
  code-owners-check:
    name: 'Check Code Owners Approvals'
    runs-on: ubuntu-latest
    
    # Skip if the PR is from Dependabot (optional - can be removed if you want to check Dependabot PRs too)
    if: github.actor != 'dependabot[bot]'
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          # We need the full history to access CODEOWNERS from the base branch
          fetch-depth: 0
          
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: 'Install Dependencies'
        run: yarn install --frozen-lockfile
        
      - name: 'Build Action'
        run: yarn build
        
      - name: 'Run Code Owners Bot'
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          # Additional context for debugging
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
